from pathlib import Path
import json


OUT = Path(__file__).resolve().parent / "rag_corpus.jsonl"


MODELS = [
    {
        "name": "iPhone 2G",
        "year": 2007,
        "screen": "Màn hình 3.5-inch LCD cảm ứng đa điểm, thiết kế nguyên bản của iPhone đời đầu.",
        "chip": "Nền tảng đời đầu dùng vi xử lý ARM11, tối ưu cho nghe gọi, duyệt web và nhạc.",
        "network": "Chỉ có 2G EDGE, chưa có App Store và chưa hỗ trợ 3G.",
        "camera": "Camera sau 2MP, không có camera trước.",
        "biometrics": "Không có Face ID hay Touch ID.",
        "port": "Cổng dock 30-pin và jack tai nghe 3.5mm.",
        "durability": "Khung kim loại và mặt lưng nhựa đen đặc trưng, mang tính lịch sử hơn là hiện đại.",
        "battery": "Pin đủ cho nhu cầu cơ bản thời đó, ưu tiên thoại, nhạc và Safari.",
        "audience": "Phù hợp cho người thích sưu tầm, nghiên cứu lịch sử iPhone.",
    },
    {
        "name": "iPhone 3G",
        "year": 2008,
        "screen": "Màn hình 3.5-inch LCD, giữ triết lý nhỏ gọn của thế hệ đầu.",
        "chip": "Tối ưu hơn đời 2G cho chạy app và duyệt web, nhưng vẫn là thế hệ sớm.",
        "network": "Điểm nhấn là có 3G và mở rộng hệ sinh thái App Store.",
        "camera": "Camera sau 2MP, vẫn chưa có camera trước.",
        "biometrics": "Không có Face ID hay Touch ID.",
        "port": "Dock 30-pin, vẫn có jack 3.5mm.",
        "durability": "Mặt lưng nhựa cong giúp cầm dễ hơn, phong cách thiết kế rất khác đời 2G.",
        "battery": "Ổn cho tác vụ cơ bản, nhưng chưa phải máy pin trâu.",
        "audience": "Phù hợp cho ai muốn hiểu giai đoạn iPhone bắt đầu bùng nổ ứng dụng.",
    },
    {
        "name": "iPhone 3GS",
        "year": 2009,
        "screen": "Màn hình 3.5-inch LCD, trải nghiệm gần như 3G nhưng mượt hơn nhờ phần cứng mạnh hơn.",
        "chip": "Hiệu năng nhanh hơn rõ rệt, nổi bật ở tốc độ mở app và phản hồi hệ thống.",
        "network": "Có 3G, Wi-Fi và trải nghiệm App Store ổn định hơn.",
        "camera": "Camera sau được cải thiện, có khả năng quay video - điểm mới rất quan trọng thời đó.",
        "biometrics": "Không có Face ID hay Touch ID.",
        "port": "Dock 30-pin, jack 3.5mm.",
        "durability": "Thiết kế bo tròn, thân thiện khi cầm nắm.",
        "battery": "Thực tế hơn 3G nhờ tối ưu phần cứng, nhưng vẫn là máy cổ điển.",
        "audience": "Phù hợp với người muốn xem bước chuyển từ iPhone sơ khai sang iPhone mượt hơn.",
    },
    {
        "name": "iPhone 4",
        "year": 2010,
        "screen": "Retina 3.5-inch, độ nét tăng mạnh so với thế hệ trước.",
        "chip": "A4 cho hiệu năng ổn định hơn và mở ra thời kỳ iPhone tự thiết kế chip.",
        "network": "3G, Wi-Fi, vẫn chưa có 4G/LTE.",
        "camera": "Camera sau 5MP, có FaceTime camera trước - bước tiến lớn về gọi video.",
        "biometrics": "Không có Face ID hay Touch ID.",
        "port": "Dock 30-pin, jack 3.5mm.",
        "durability": "Thiết kế kính trước sau và khung thép phẳng rất nhận diện.",
        "battery": "Cân bằng hơn đời trước, hợp với màn hình Retina nhỏ gọn.",
        "audience": "Hợp với người thích thiết kế kinh điển và mốc lịch sử Retina.",
    },
    {
        "name": "iPhone 4S",
        "year": 2011,
        "screen": "Retina 3.5-inch, giữ form quen thuộc nhưng tối ưu hiển thị.",
        "chip": "A5 giúp máy mượt hơn, mở ra trải nghiệm Siri và app nặng hơn.",
        "network": "3G, chưa có LTE nhưng tốc độ thực tế tốt hơn đời trước.",
        "camera": "Camera sau 8MP, chất lượng ảnh và video được nâng rõ.",
        "biometrics": "Không có Face ID hay Touch ID.",
        "port": "Dock 30-pin, jack 3.5mm.",
        "durability": "Khung kính-thép tiếp tục là dấu ấn thiết kế.",
        "battery": "Đủ dùng cho nhu cầu thường ngày của giai đoạn đó.",
        "audience": "Hợp với người thích Siri, camera ổn hơn và thiết kế cổ điển.",
    },
    {
        "name": "iPhone 5",
        "year": 2012,
        "screen": "Màn hình 4-inch, dài hơn và thoáng hơn để đọc nội dung.",
        "chip": "A6 mang lại hiệu năng tốt, đủ cho iOS và app thời bấy giờ.",
        "network": "Có LTE, tiến lên đời kết nối nhanh hơn.",
        "camera": "Camera sau 8MP, chụp nhanh và ổn định hơn.",
        "biometrics": "Không có Face ID hay Touch ID.",
        "port": "Bước sang Lightning, vẫn có jack 3.5mm.",
        "durability": "Vỏ nhôm mỏng nhẹ, mang phong cách hiện đại hơn hẳn.",
        "battery": "Mỏng nhẹ nên pin ở mức vừa đủ, tối ưu cho tính di động.",
        "audience": "Phù hợp người thích máy gọn, nhẹ, và là cột mốc Lightning.",
    },
    {
        "name": "iPhone 5c",
        "year": 2013,
        "screen": "Màn hình 4-inch LCD, cùng kích thước với iPhone 5.",
        "chip": "Nền tảng tương tự thế hệ 5, phục vụ nhu cầu cơ bản và ổn định.",
        "network": "LTE, Wi-Fi, đủ cho nhu cầu phổ thông.",
        "camera": "Camera sau 8MP, chất lượng quen thuộc của dòng cùng thời.",
        "biometrics": "Không có Face ID hay Touch ID.",
        "port": "Lightning.",
        "durability": "Vỏ polycarbonate nhiều màu, bền kiểu thân thiện và trẻ trung.",
        "battery": "Mức pin tương đương phân khúc phổ thông cùng thời.",
        "audience": "Phù hợp người thích màu sắc và hình thức trẻ trung.",
    },
    {
        "name": "iPhone 5s",
        "year": 2013,
        "screen": "Màn hình 4-inch, nhỏ gọn nhưng hoàn thiện hơn iPhone 5.",
        "chip": "A7 64-bit và chip đồng xử lý M7, là bước ngoặt lớn về kiến trúc.",
        "network": "LTE và Wi-Fi ổn định hơn.",
        "camera": "Camera sau 8MP, cải thiện xử lý ảnh và video.",
        "biometrics": "Touch ID là điểm nhấn bảo mật lớn.",
        "port": "Lightning.",
        "durability": "Thân kim loại sang hơn 5c, cầm chắc tay.",
        "battery": "Tối ưu tốt hơn cho nhu cầu sử dụng hằng ngày.",
        "audience": "Hợp với người thích máy nhỏ, có Touch ID và giá trị lịch sử cao.",
    },
    {
        "name": "iPhone 6",
        "year": 2014,
        "screen": "4.7-inch Retina HD, mở đầu xu hướng màn hình lớn hơn.",
        "chip": "A8 cho hiệu năng tốt hơn và tiêu thụ điện hợp lý hơn.",
        "network": "LTE, Wi-Fi, bắt đầu phù hợp nhu cầu nội dung nhiều hơn.",
        "camera": "Camera sau 8MP với xử lý ảnh tốt hơn đời trước.",
        "biometrics": "Touch ID.",
        "port": "Lightning.",
        "durability": "Thân nhôm bo cong, mỏng và nhẹ hơn đời trước.",
        "battery": "Dùng ổn cho nhu cầu phổ thông, nhưng không phải pin trâu.",
        "audience": "Hợp với người thích máy lớn hơn iPhone 5s nhưng vẫn dễ cầm.",
    },
    {
        "name": "iPhone 6 Plus",
        "year": 2014,
        "screen": "5.5-inch Retina HD, lớn hơn để xem video và đọc nội dung.",
        "chip": "A8 với không gian hiển thị lớn, phù hợp giải trí.",
        "network": "LTE, Wi-Fi.",
        "camera": "Camera sau 8MP, có chống rung quang học tốt hơn bản thường.",
        "biometrics": "Touch ID.",
        "port": "Lightning.",
        "durability": "Thân máy lớn, nhôm bo cong; là một trong những iPhone màn hình lớn đầu tiên.",
        "battery": "Lợi thế pin so với bản 6 do thân máy lớn hơn.",
        "audience": "Phù hợp người thích màn hình to và pin tốt hơn đời 6.",
    },
    {
        "name": "iPhone 6s",
        "year": 2015,
        "screen": "4.7-inch Retina HD, bổ sung 3D Touch.",
        "chip": "A9 mạnh hơn rõ rệt, mượt và ổn định cho nhiều năm.",
        "network": "LTE, Wi-Fi.",
        "camera": "Camera sau 12MP, nâng cấp lớn so với 8MP.",
        "biometrics": "Touch ID.",
        "port": "Lightning.",
        "durability": "Nhôm series 7000 cứng cáp hơn, giảm lo ngại uốn cong.",
        "battery": "Cân bằng giữa hiệu năng và thời lượng pin.",
        "audience": "Hợp với người cần máy nhỏ nhưng mạnh hơn, camera tốt hơn.",
    },
    {
        "name": "iPhone 6s Plus",
        "year": 2015,
        "screen": "5.5-inch Retina HD, lớn và có 3D Touch.",
        "chip": "A9, mượt cho đa nhiệm và game nhẹ.",
        "network": "LTE, Wi-Fi.",
        "camera": "Camera sau 12MP, có chống rung quang học.",
        "biometrics": "Touch ID.",
        "port": "Lightning.",
        "durability": "Thân máy lớn, nhôm cứng hơn đời 6 Plus.",
        "battery": "Pin tốt hơn bản 6s thường nhờ kích thước lớn.",
        "audience": "Hợp với ai muốn màn hình to nhưng vẫn giữ Touch ID.",
    },
    {
        "name": "iPhone 7",
        "year": 2016,
        "screen": "4.7-inch Retina HD, sáng hơn và màu sắc tốt hơn.",
        "chip": "A10 Fusion giúp hiệu năng và tiết kiệm pin tốt hơn.",
        "network": "LTE, Wi-Fi, bắt đầu phù hợp streaming nhiều hơn.",
        "camera": "Camera sau 12MP, cải thiện chống rung và màu sắc.",
        "biometrics": "Touch ID.",
        "port": "Lightning, loại bỏ jack 3.5mm.",
        "durability": "Kháng nước/bụi tốt hơn, thân máy cứng cáp hơn.",
        "battery": "Cải thiện so với 6s, nhất là trải nghiệm hằng ngày.",
        "audience": "Hợp với người muốn máy cổ điển nhưng đã bỏ jack tai nghe.",
    },
    {
        "name": "iPhone 7 Plus",
        "year": 2016,
        "screen": "5.5-inch Retina HD, tối ưu cho xem nội dung.",
        "chip": "A10 Fusion, mạnh và đủ bền bỉ.",
        "network": "LTE, Wi-Fi.",
        "camera": "Dual camera 12MP là điểm nhấn, có zoom quang học và chân dung.",
        "biometrics": "Touch ID.",
        "port": "Lightning, không còn jack 3.5mm.",
        "durability": "Kháng nước/bụi và hoàn thiện tốt hơn đời trước.",
        "battery": "Pin thường tốt hơn bản nhỏ nhờ thân máy lớn.",
        "audience": "Hợp với ai thích chụp chân dung và màn hình lớn.",
    },
    {
        "name": "iPhone 8",
        "year": 2017,
        "screen": "4.7-inch Retina HD, màu sắc và True Tone tốt hơn.",
        "chip": "A11 Bionic, hiệu năng rất mạnh so với thời điểm ra mắt.",
        "network": "LTE, Wi-Fi.",
        "camera": "Camera sau 12MP, quay/chụp ổn định và hỗ trợ sạc không dây ở mặt lưng kính.",
        "biometrics": "Touch ID.",
        "port": "Lightning và hỗ trợ sạc không dây.",
        "durability": "Mặt lưng kính và khung nhôm, IP67.",
        "battery": "Tối ưu tốt hơn, ổn cho người thích máy nhỏ.",
        "audience": "Hợp với người thích Touch ID nhưng muốn phần cứng mới hơn iPhone 7.",
    },
    {
        "name": "iPhone 8 Plus",
        "year": 2017,
        "screen": "5.5-inch Retina HD, có True Tone và màu sắc tốt.",
        "chip": "A11 Bionic.",
        "network": "LTE, Wi-Fi.",
        "camera": "Dual camera 12MP, chụp chân dung và zoom tốt hơn.",
        "biometrics": "Touch ID.",
        "port": "Lightning và sạc không dây.",
        "durability": "Mặt lưng kính, IP67.",
        "battery": "Thường tốt hơn bản nhỏ nhờ thân máy lớn.",
        "audience": "Hợp với người thích màn hình lớn nhưng vẫn muốn Touch ID.",
    },
    {
        "name": "iPhone X",
        "year": 2017,
        "screen": "5.8-inch OLED Super Retina, mở ra kỷ nguyên notch và viền mỏng.",
        "chip": "A11 Bionic.",
        "network": "LTE, Wi-Fi.",
        "camera": "Dual camera 12MP, Face ID và camera trước phục vụ nhận diện khuôn mặt.",
        "biometrics": "Face ID thay cho Touch ID.",
        "port": "Lightning.",
        "durability": "Thiết kế kính-thép rất cao cấp, IP67.",
        "battery": "Cân bằng tốt cho máy OLED đầu tiên của Apple.",
        "audience": "Hợp với người thích thiết kế hiện đại và Face ID.",
    },
    {
        "name": "iPhone XR",
        "year": 2018,
        "screen": "6.1-inch LCD Liquid Retina, màn hình lớn nhưng tối ưu chi phí.",
        "chip": "A12 Bionic.",
        "network": "LTE, Wi-Fi.",
        "camera": "Một camera sau 12MP nhưng xử lý ảnh tốt, chụp đời thường ổn.",
        "biometrics": "Face ID.",
        "port": "Lightning.",
        "durability": "Khung nhôm, nhiều màu, IP67.",
        "battery": "Nổi tiếng là pin tốt trong phân khúc thời điểm đó.",
        "audience": "Hợp với người thích màn hình lớn, pin tốt, giá dễ chịu hơn dòng X/XS.",
    },
    {
        "name": "iPhone XS Max",
        "year": 2018,
        "screen": "6.5-inch OLED Super Retina, lớn và cao cấp hơn XR.",
        "chip": "A12 Bionic.",
        "network": "LTE, Wi-Fi.",
        "camera": "Dual camera 12MP, chụp ảnh linh hoạt và zoom tốt hơn.",
        "biometrics": "Face ID.",
        "port": "Lightning.",
        "durability": "Khung thép và kính, IP68.",
        "battery": "Pin lớn hơn bản XS, hợp người dùng màn hình to.",
        "audience": "Hợp với người muốn trải nghiệm flagship OLED lớn.",
    },
    {
        "name": "iPhone 11 Pro Max",
        "year": 2019,
        "screen": "6.5-inch OLED Super Retina XDR, hiển thị sáng và giàu tương phản hơn.",
        "chip": "A13 Bionic.",
        "network": "LTE, Wi-Fi.",
        "camera": "Triple camera 12MP, chụp góc rộng/siêu rộng/tele rất linh hoạt.",
        "biometrics": "Face ID.",
        "port": "Lightning.",
        "durability": "Kính mờ mặt lưng và IP68.",
        "battery": "Rất mạnh trong thế hệ của nó, nổi tiếng pin tốt.",
        "audience": "Hợp với người chụp ảnh nhiều và muốn pin trâu thời kỳ đó.",
    },
    {
        "name": "iPhone 12 Pro Max",
        "year": 2020,
        "screen": "6.7-inch OLED, viền phẳng và Ceramic Shield ở mặt trước.",
        "chip": "A14 Bionic.",
        "network": "Có 5G, Wi-Fi và định hướng kết nối nhanh hơn.",
        "camera": "Triple camera 12MP + LiDAR, chụp đêm và lấy nét tốt hơn.",
        "biometrics": "Face ID.",
        "port": "Lightning, hỗ trợ MagSafe.",
        "durability": "Thiết kế phẳng, Ceramic Shield, IP68.",
        "battery": "Thời lượng tốt, đủ cho ngày dài với màn hình lớn.",
        "audience": "Hợp với người muốn Pro Max đầu tiên của kỷ nguyên 5G.",
    },
    {
        "name": "iPhone 13 Pro Max",
        "year": 2021,
        "screen": "6.7-inch OLED Super Retina XDR với ProMotion 120Hz.",
        "chip": "A15 Bionic.",
        "network": "5G, Wi-Fi.",
        "camera": "Triple camera 12MP, Cinematic mode và cải thiện chụp thiếu sáng.",
        "biometrics": "Face ID.",
        "port": "Lightning, MagSafe.",
        "durability": "Khung thép, IP68, thiết kế rất chắc chắn.",
        "battery": "Nổi tiếng pin rất tốt trong các đời Pro Max.",
        "audience": "Hợp với người cần màn hình mượt, pin mạnh và camera cân bằng.",
    },
    {
        "name": "iPhone 14 Pro Max",
        "year": 2022,
        "screen": "6.7-inch OLED ProMotion, Dynamic Island thay cho notch truyền thống.",
        "chip": "A16 Bionic.",
        "network": "5G, Wi-Fi.",
        "camera": "Camera chính 48MP, chụp đêm và crop linh hoạt hơn.",
        "biometrics": "Face ID.",
        "port": "Lightning, MagSafe.",
        "durability": "Khung thép, kính Ceramic Shield, IP68.",
        "battery": "Rất mạnh và phù hợp người dùng cường độ cao.",
        "audience": "Hợp với người thích camera mạnh, màn hình lớn và Dynamic Island.",
    },
    {
        "name": "iPhone 15 Pro Max",
        "year": 2023,
        "screen": "6.7-inch OLED ProMotion, viền mỏng hơn và khung titan.",
        "chip": "A17 Pro.",
        "network": "5G, Wi-Fi.",
        "camera": "Camera chính 48MP, tele 5x trên bản Pro Max, USB-C linh hoạt hơn.",
        "biometrics": "Face ID.",
        "port": "USB-C, hỗ trợ truyền dữ liệu và sạc tiện hơn Lightning.",
        "durability": "Khung titan, nhẹ và cao cấp, IP68.",
        "battery": "Thuộc nhóm pin rất tốt trong phân khúc cao cấp.",
        "audience": "Hợp với người cần hiệu năng mạnh, cổng USB-C và zoom xa.",
    },
    {
        "name": "iPhone 16 Pro Max",
        "year": 2024,
        "screen": "6.9-inch OLED ProMotion, lớn nhất trong dòng Pro thời điểm đó.",
        "chip": "A18 Pro.",
        "network": "5G, Wi-Fi.",
        "camera": "Camera cao cấp với Camera Control, tối ưu cho chụp/quay nhanh hơn.",
        "biometrics": "Face ID.",
        "port": "USB-C.",
        "durability": "Khung titan, IP68, độ hoàn thiện cao cấp.",
        "battery": "Mạnh cho người dùng chuyên nghiệp và quay chụp nhiều.",
        "audience": "Hợp với người muốn màn hình lớn, hiệu năng mạnh và trải nghiệm Pro mới.",
    },
    {
        "name": "iPhone 17 Pro Max",
        "year": 2025,
        "screen": "6.9-inch OLED Super Retina XDR, ProMotion 120Hz, độ sáng ngoài trời rất cao.",
        "chip": "A19 Pro, tối ưu cho hiệu năng và tác vụ AI/đồ họa nặng.",
        "network": "5G và Wi-Fi thế hệ mới.",
        "camera": "18MP Center Stage front camera và cụm 48MP Fusion, zoom tới 8x trên dòng Pro.",
        "biometrics": "Face ID.",
        "port": "USB-C.",
        "durability": "Thiết kế unibody nhôm với tản nhiệt vapor chamber, Ceramic Shield 2, IP68.",
        "battery": "Tập trung vào pin lâu và sạc nhanh hơn so với thế hệ trước.",
        "audience": "Hợp với người cần flagship lớn nhất, mạnh nhất, chụp quay chuyên nghiệp nhất.",
    },
]


QUESTION_TEMPLATES = [
    ("ra_mo", "iPhone {name} ra mắt năm nào?", lambda s: f"iPhone {s['name']} ra mắt năm {s['year']}."),
    ("man_hinh", "Màn hình của {name} có gì đáng chú ý?", lambda s: f"Màn hình của {s['name']}: {s['screen']}"),
    ("chip", "Chip xử lý của {name} là gì?", lambda s: f"Chip xử lý của {s['name']}: {s['chip']}"),
    ("ket_noi", "Máy có hỗ trợ 5G không?", lambda s: f"Kết nối của {s['name']}: {s['network']}"),
    ("camera", "Camera của {name} có gì nổi bật?", lambda s: f"Camera của {s['name']}: {s['camera']}"),
    ("biometrics", "Máy dùng Face ID hay Touch ID?", lambda s: f"Bảo mật của {s['name']}: {s['biometrics']}"),
    ("cong_sac", "Cổng sạc/kết nối chính là gì?", lambda s: f"Cổng/kết nối của {s['name']}: {s['port']}"),
    ("do_ben", "Máy có chống nước hay độ bền tốt không?", lambda s: f"Độ bền của {s['name']}: {s['durability']}"),
    ("pin_hieu_nang", "Pin/hiệu năng của {name} thế nào?", lambda s: f"Pin và hiệu năng của {s['name']}: {s['battery']}"),
    ("phu_hop", "Máy phù hợp với ai?", lambda s: f"Phù hợp với {s['name']}: {s['audience']}"),
]


def main() -> None:
    records = []
    idx = 1
    for spec in MODELS:
        display_name = spec["name"].replace("iPhone ", "")
        answer_spec = dict(spec)
        answer_spec["name"] = display_name
        for topic, q_tmpl, a_fn in QUESTION_TEMPLATES:
            question = q_tmpl.format(name=display_name)
            answer = a_fn(answer_spec)
            records.append(
                {
                    "id": f"iphone-{idx:04d}",
                    "text": f"Hỏi: {question}\nĐáp: {answer}",
                    "metadata": {
                        "source": "iphone_rag_synthetic",
                        "lang": "vi",
                        "family": spec["name"],
                        "topic": topic,
                    },
                }
            )
            idx += 1

    with OUT.open("w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"wrote {len(records)} records to {OUT}")


if __name__ == "__main__":
    main()
