services:
  backend:
    image: media_tech_ai:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media_tech_ai_backend
    working_dir: /workspace/backend
    volumes:
      - ../../..:/workspace
    environment:
      PORT: "8006"
    entrypoint: ["node"]
    command: ["server.js"]

  openclaw:
    image: media_tech_ai_openclaw:latest
    build:
      context: ../../openclaw
      dockerfile: Dockerfile
    container_name: media_tech_ai_openclaw
    working_dir: /workspace/server/openclaw
    environment:
      PORT: "8802"
      WS_PATH: "/chatbot/gpu"
      OPENCLAW_CONFIG_PATH: "/workspace/server/openclaw/config.json"
    ports:
      - "8802:8802"
    entrypoint: ["node"]
    command: ["openclaw.js"]

  frontend:
    image: media_tech_ai:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media_tech_ai_fontend
    working_dir: /workspace/fontend
    volumes:
      - ../../..:/workspace
    environment:
      PORT: "8008"
      HOST: "0.0.0.0"
      CHAT_API_URL: "http://backend:8006/chat_bot/api"
      NUXT_PUBLIC_CHAT_API_URL: "http://backend:8006/chat_bot/api"
    entrypoint: ["node"]
    command: [".output/server/index.mjs"]
    ports:
      - "8008:8008"
